### ISSUE TITLE
Should take this down

### ISSUE THREAD

**Issue by Sammons** [SomMeri/matasano-cryptopals-solutions#2]
Part of the point of these challenges is that there isn't a solution. Having these right here as the 3rd link on google takes away the value of the cryptopals challenges for others. That's my opinion... but in the front page of the site they describe how when it was in email form they asked people not to divulge the answers.

**Comment by SomMeri** [comment]
The competition is not running anymore and solutions are not secret anymore. Matasano even collected our permissions to publish our solutions with plan to [host solutions on their own site](http://cryptopals.com/). 

They never finished the page, but they clearly did not intended the solutions to be secret after the competition was over.
