### ISSUE TITLE
problem with shiro

### ISSUE THREAD

**Issue by kylarstar** [SomMeri/matasano-cryptopals-solutions#3]
hey there, first of all ty for the code. But i got a Problem with Shiro, i installed it as i have been told to by their website. but how can i access their librarys? Can't find anything useful on the web.
Greetings

**Comment by SomMeri** [comment]
What did you installed? The only think you should need to install in order to run this repo is maven and java. Maven then downloads all dependencies by itself including Shiro when you run `mvn clean install` or trigger it from IDE.
